name: Generate OpenAPI Spec and Upload to Bump.sh

on:
  push:
    branches:
      - master 

jobs:
  generate_and_upload_spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Start Spring Boot App
        run: |
          ./mvnw clean install
          nohup ./mvnw spring-boot:run &  # Run Spring Boot in background

      - name: Wait for Spring Boot to start
        run: sleep 60 

      - name: Generate OpenAPI Spec
        run: |
          # Fetch the OpenAPI spec from the Spring Boot application
          curl -o docs/openapi/openapi-spec.json http://localhost:8080/v3/api-docs

      - name: Upload to Bump.sh
        uses: bump-sh/bump-action@v1  # Make sure you replace with actual Bump.sh action
        with:
          api_token: BWk96UK1iFSJgmYGpk5p9YdHgfX8eCRE
          spec_file: docs/openapi/openapi-spec.json
