name: Generate OpenAPI Specification

on:
  push:
    branches:
      - master

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Executable Permission for mvnw
        run: chmod +x ./mvnw

      - name: Build the project
        run: ./mvnw clean install

      - name: Run Spring Boot App in Background
        working-directory: ./web
        run: |
          nohup ./mvnw spring-boot:run > ../../spring.log 2>&1 &

      - name: Wait for Spring Boot to Start
        run: sleep 40

      - name: Print Spring Boot Logs
        run: cat spring.log

      - name: Try curl for OpenAPI Spec
        run: |
          curl -v http://localhost:8080/v3/api-docs
          curl -o api-docs.yml http://localhost:8080/v3/api-docs

      - name: Upload OpenAPI Spec as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: api-docs.yml