name: Generate OpenAPI Specification

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  generate_openapi:
    runs-on: ubuntu-latest  # Run on an Ubuntu-based VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu' 

      - name: Build with Maven
        run: ./mvnw clean install 

      - name: Run Spring Boot Application in Background
        run: |
          nohup ./mvnw spring-boot:run &  # Run Spring Boot in background

      - name: Wait for Spring Boot to start
        run: sleep 40

      - name: Generate OpenAPI Spec
        run: |
          curl -o api-docs.yml http://localhost:8080/v3/api-docs  # Fetch the OpenAPI spec

      - name: Upload OpenAPI Spec as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openapi-spec
          path: api-docs.yml  # Upload the generated OpenAPI spec
