name: Generate OpenAPI Specification

on:
  push:
    branches:
      - master

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build only the web module
        run: ./mvnw clean install -pl web -am

      - name: Run Spring Boot app in background
        run: |
          nohup ./mvnw spring-boot:run -pl web > spring.log 2>&1 &

      - name: Wait for the app to start
        run: sleep 20

      - name: Print Spring Boot logs
        run: cat spring.log || echo "Log file not found"

      - name: Download OpenAPI spec
        run: |
          curl -v http://localhost:8080/v3/api-docs
          curl -o api-docs.yml http://localhost:8080/v3/api-docs

      - name: Upload OpenAPI Spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: api-docs.yml