name: Generate OpenAPI Specification

on:
  push:
    branches:
      - master

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build only the web module
        run: ./mvnw clean install -pl web -am

      - name: Run Spring Boot app in background
        run: |
          nohup ./mvnw spring-boot:run -pl web > spring.log 2>&1 &

      - name: Wait for the app to be ready
        run: |
          for i in {1..20}; do
            curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' && break
            echo "Waiting for app..."
            sleep 5
          done

      - name: Download OpenAPI spec
        run: |
          curl -o api-docs.yml http://localhost:8080/v3/api-docs

      - name: Deploy OpenAPI spec to Bump.sh
        uses: bump-sh/github-action@v1
        with:
          doc: hotel-reservation
          token: ${ secrets.BUMP_TOKEN }
          file: api-docs.yml